[package]
authors = ["David Flemström <dflemstr@spotify.com>"]
name = "b"
version = "0.1.0"

[dependencies.error-chain]
git = "https://github.com/brson/error-chain.git"

[dependencies.a]
path = "../a"
